// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGGSG74FinJwcYamFN46C5h-fYDLg5nIY',
    appId: '1:816320288314:web:eb067d749a379433f68703',
    messagingSenderId: '816320288314',
    projectId: 'digiceets-database',
    authDomain: 'digiceets-database.firebaseapp.com',
    storageBucket: 'digiceets-database.appspot.com',
    measurementId: 'G-S4X546969Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgXgMQEx2nkiYj6C5bHPguqrUpl2OPYHQ',
    appId: '1:816320288314:android:a9b5c4c9ffca992df68703',
    messagingSenderId: '816320288314',
    projectId: 'digiceets-database',
    storageBucket: 'digiceets-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC73-ez6dN8u9SlS3Suud4tQRfQ_a8ylXg',
    appId: '1:816320288314:ios:948038453e179a50f68703',
    messagingSenderId: '816320288314',
    projectId: 'digiceets-database',
    storageBucket: 'digiceets-database.appspot.com',
    androidClientId: '816320288314-p29h3s6mu3vicp1ejhhmfjen8m6te9mu.apps.googleusercontent.com',
    iosClientId: '816320288314-05l1eqg7148l308c820ee4fok092mf7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC73-ez6dN8u9SlS3Suud4tQRfQ_a8ylXg',
    appId: '1:816320288314:ios:7517ac124ee87c09f68703',
    messagingSenderId: '816320288314',
    projectId: 'digiceets-database',
    storageBucket: 'digiceets-database.appspot.com',
    androidClientId: '816320288314-p29h3s6mu3vicp1ejhhmfjen8m6te9mu.apps.googleusercontent.com',
    iosClientId: '816320288314-iogqo8qrtjpraku3s84nli49j1abr7md.apps.googleusercontent.com',
    iosBundleId: 'com.example.main.RunnerTests',
  );
}
